package com.explitech.littlecopy.dao;

import com.explitech.littlecopy.model.Leadtime;
import com.explitech.littlecopy.model.LeadtimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeadtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int countByExample(LeadtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByExample(LeadtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByPrimaryKey(Integer leadtimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insert(Leadtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insertSelective(Leadtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    List<Leadtime> selectByExample(LeadtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    Leadtime selectByPrimaryKey(Integer leadtimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") Leadtime record, @Param("example") LeadtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExample(@Param("record") Leadtime record, @Param("example") LeadtimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKeySelective(Leadtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leadtime
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKey(Leadtime record);
}