package com.explitech.littlecopy.dao;

import com.explitech.littlecopy.model.Revenue;
import com.explitech.littlecopy.model.RevenueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RevenueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int countByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByPrimaryKey(Integer revenueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insert(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insertSelective(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    List<Revenue> selectByExample(RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    Revenue selectByPrimaryKey(Integer revenueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") Revenue record, @Param("example") RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExample(@Param("record") Revenue record, @Param("example") RevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKeySelective(Revenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revenue
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKey(Revenue record);
}