package com.explitech.littlecopy.dao;

import com.explitech.littlecopy.model.Utilization;
import com.explitech.littlecopy.model.UtilizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UtilizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int countByExample(UtilizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByExample(UtilizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insert(Utilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int insertSelective(Utilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    List<Utilization> selectByExample(UtilizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    Utilization selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") Utilization record, @Param("example") UtilizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByExample(@Param("record") Utilization record, @Param("example") UtilizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKeySelective(Utilization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utilization
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    int updateByPrimaryKey(Utilization record);
}