package com.explitech.littlecopy.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.config_value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String configValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_id
     *
     * @return the value of config.config_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_id
     *
     * @param configId the value for config.config_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_name
     *
     * @return the value of config.config_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_name
     *
     * @param configName the value for config.config_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setConfigName(String configName) {
        this.configName = configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.config_value
     *
     * @return the value of config.config_value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.config_value
     *
     * @param configValue the value for config.config_value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }
}