package com.explitech.littlecopy.model;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonView;

import com.explitech.littlecopy.common.ServiceObjectView;

public class Leadtime implements Serializable  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leadtime.leadtime_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.LeadtimeView.class)
    private Integer leadtimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leadtime.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.LeadtimeView.class)
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leadtime.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.LeadtimeView.class)
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leadtime.leadtime_id
     *
     * @return the value of leadtime.leadtime_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getLeadtimeId() {
        return leadtimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leadtime.leadtime_id
     *
     * @param leadtimeId the value for leadtime.leadtime_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setLeadtimeId(Integer leadtimeId) {
        this.leadtimeId = leadtimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leadtime.date
     *
     * @return the value of leadtime.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leadtime.date
     *
     * @param date the value for leadtime.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leadtime.value
     *
     * @return the value of leadtime.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leadtime.value
     *
     * @param value the value for leadtime.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }
}