package com.explitech.littlecopy.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_start_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Date orderStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_end_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Date orderEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer contractTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_start_date
     *
     * @return the value of order.order_start_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getOrderStartDate() {
        return orderStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_start_date
     *
     * @param orderStartDate the value for order.order_start_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setOrderStartDate(Date orderStartDate) {
        this.orderStartDate = orderStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_end_date
     *
     * @return the value of order.order_end_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getOrderEndDate() {
        return orderEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_end_date
     *
     * @param orderEndDate the value for order.order_end_date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setOrderEndDate(Date orderEndDate) {
        this.orderEndDate = orderEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.contract_type_id
     *
     * @return the value of order.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getContractTypeId() {
        return contractTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.contract_type_id
     *
     * @param contractTypeId the value for order.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setContractTypeId(Integer contractTypeId) {
        this.contractTypeId = contractTypeId;
    }
}