package com.explitech.littlecopy.model;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonView;

import com.explitech.littlecopy.common.ServiceObjectView;

public class OrderHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.history_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.OrderHistoryView.class)
    private Integer historyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.OrderHistoryView.class)
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_history.order_number
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.OrderHistoryView.class)
    private String orderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.history_id
     *
     * @return the value of order_history.history_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.history_id
     *
     * @param historyId the value for order_history.history_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.date
     *
     * @return the value of order_history.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.date
     *
     * @param date the value for order_history.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_history.order_number
     *
     * @return the value of order_history.order_number
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_history.order_number
     *
     * @param orderNumber the value for order_history.order_number
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
}