package com.explitech.littlecopy.model;

import java.util.Date;

public class Revenue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.revenue_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer revenueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer contractTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revenue.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.revenue_id
     *
     * @return the value of revenue.revenue_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getRevenueId() {
        return revenueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.revenue_id
     *
     * @param revenueId the value for revenue.revenue_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setRevenueId(Integer revenueId) {
        this.revenueId = revenueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.contract_type_id
     *
     * @return the value of revenue.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getContractTypeId() {
        return contractTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.contract_type_id
     *
     * @param contractTypeId the value for revenue.contract_type_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setContractTypeId(Integer contractTypeId) {
        this.contractTypeId = contractTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.date
     *
     * @return the value of revenue.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.date
     *
     * @param date the value for revenue.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revenue.value
     *
     * @return the value of revenue.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revenue.value
     *
     * @param value the value for revenue.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }
}