package com.explitech.littlecopy.model;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonView;

import com.explitech.littlecopy.common.ServiceObjectView;

public class Storage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.StorageView.class)
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.StorageView.class)
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.current
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
	@JsonView(ServiceObjectView.StorageView.class)
    private String current;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.record_id
     *
     * @return the value of storage.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.record_id
     *
     * @param recordId the value for storage.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.date
     *
     * @return the value of storage.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.date
     *
     * @param date the value for storage.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.current
     *
     * @return the value of storage.current
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.current
     *
     * @param current the value for storage.current
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setCurrent(String current) {
        this.current = current;
    }
}