package com.explitech.littlecopy.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.use_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String useName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.use_name
     *
     * @return the value of user.use_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getUseName() {
        return useName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.use_name
     *
     * @param useName the value for user.use_name
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setUseName(String useName) {
        this.useName = useName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}