package com.explitech.littlecopy.model;

import java.util.Date;

public class Utilization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utilization.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utilization.step
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Integer step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utilization.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utilization.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utilization.record_id
     *
     * @return the value of utilization.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utilization.record_id
     *
     * @param recordId the value for utilization.record_id
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utilization.step
     *
     * @return the value of utilization.step
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utilization.step
     *
     * @param step the value for utilization.step
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utilization.date
     *
     * @return the value of utilization.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utilization.date
     *
     * @param date the value for utilization.date
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utilization.value
     *
     * @return the value of utilization.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utilization.value
     *
     * @param value the value for utilization.value
     *
     * @mbggenerated Wed Mar 23 17:19:09 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }
}